project:
  type: website
  output-dir: _site

website:
  title: "Computational Social Science Textbook"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Tutorials
        href: Tutorials/index.qmd

  sidebar:
    - title: "Tutorials"
      contents:
        - Tutorials/index.qmd
        - Tutorials/Intro-to-R.qmd
        - Tutorials/Data-structure-and-cleaning.qmd

format:
  html:
    toc: true
