project:
  type: website
  output-dir: _site

website:
  title: "Computational Social Science Textbook"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Tutorials
        href: Tutorials/index.qmd

  sidebar:
    - title: "Tutorials"
      contents:
        - Tutorials/index.qmd
        - Tutorials/Intro-to-R.qmd
        - Tutorials/Data-structure-and-cleaning.qmd
        - Tutorials/Data-preprocessing.qmd
        - Tutorials/Data-access.qmd

format:
  html:
    theme: cosmo
    toc: true
    fontsize: 1.15em
    linestretch: 1.6
    code-overflow: wrap
    code-line-numbers: true
    code-copy: true
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow">
